### ISSUE TITLE
An example of pedigree failing to phase haplotypes.

### ISSUE THREAD

**Issue by changebio** [statgenetics/cstatgen#2]
![Screen Shot 2022-01-25 at 11 55 02 AM](https://user-images.githubusercontent.com/10182773/151036211-ef4a1dd5-dd4b-4ac7-8704-7a85e7176a38.png)

For this example, the pedigree has only two layers. But the second layer has 15 nodes.
All I can think about Cstatgen failed to phase haplotypes of the pedigree is due to too many children in the second layer.

**Comment by gaow** [comment]
Great this is a simple enough example to help debug! @changebio could you verify that if it has to do with number of leaves, or some particular behavior of a specific leaf?

**Comment by changebio** [comment]
After testing, I can quite sure that the pedigree failing to phase haplotypes is due to too many nodes in the second layer.
The following is how I do the testing.
First, I removed the 4 children (10R_R114_10,10R_R114_11,10R_R114_6,10R_R114_8), because they don't have vcfs. and it works, which means the failing is not by the genotype related reasons.
Then, each time I add one child in, it failed after I added three children in, which means that the maximum capacity is 13 children.

**Comment by gaow** [comment]
thanks @changebio . you are saying a random 13 children works, but a random 14 does not? Next question is to see where in the code it fail ...

**Comment by gaow** [comment]
@changebio one issue at a time -- just to touch base with what you found with this issue -- if it's the problem with many offspring, or particular offspring patterns

**Comment by changebio** [comment]
The issue is also caused by the limitation.
![Screen Shot 2022-02-01 at 9 52 30 AM](https://user-images.githubusercontent.com/10182773/152032820-fabbb3e8-35d8-414b-8c38-3309ea20a713.png)
 after I changed the maxBits from 24 to 36. then, it works.

**Comment by gaow** [comment]
bit 24 is hard coded. I wonder what bit you should set it to ... perhaps large enough to make it work?
